### PR TITLE
Replace Codeship with CircleCI

### PR DESCRIPTION
**Pull request by lra**
https://app.asana.com/0/368954819476/71153161928537

### CODE REVIEW

**Comment by mdaffern** [comment]
@lra please fix your code and update this PR asap!

**Comment by benauthor** [comment]
:laughing:

**Comment by lra** [comment]
@mdaffern on it!

**Comment by tabuchid** [comment]
Ha. Thanks @lra

**Comment by brentwatson** [comment]
:shipit:

**Comment by jamesob** [comment]
big +1

**Comment by heyitsnoah** [comment]
everyone's coming out of the woodwork for this one, huh?

**Comment by jamesob** [comment]
@heyitsnoah circle is just *so* much better than codeship

**Comment by lra** [comment]
I'm glad u all have fun, I'm doing this for 50+ repos 😭
10ish to go!

**Comment by sarahduve** [comment]
:clap:

**Comment by jamesob** [comment]
"microservices," they said. "way of the future," they said.

;)

**Pull request merged**
