### PR TITLE
Libraries with Cocoapods or Carthage. AFNetworking Optional

### PR DESCRIPTION
**Pull request by tabuchid**
@szweier @jac300 What do you think about this?

### CODE REVIEW

**Comment by szweier** [comment]
I'm good with the AFNetworking optional but do we want to know that they know cocoa pods specifically or do we assume either one is easy enough to pick up.

**Comment by tabuchid** [comment]
Should be easy enough to pick up. It might actually be better to just remove that requirement to see what people do.

**Comment by tabuchid** [comment]
Just realized allowing for Carthage would not be iOS 7 compatible. Does the app have any 7-8 specialization anyway? How can we properly test for that or should we test for that at a different stage?

**Comment by szweier** [comment]
I like that idea.

**Comment by szweier** [comment]
Supporting 7 & 8 is mostly to see if people are reading but there are a few things with table view cells that 8 handles better than 7 that can't be used to support both.

**Comment by tabuchid** [comment]
Right. How is it now just removing the how you install a library requirement?

**Comment by szweier** [comment]
:+1:

**Pull request merged**
