### PR TITLE
Remove submission instructions

### PR DESCRIPTION
**Pull request by tabuchid**
I originally thought it would be good to know they used git and its interesting to see what they write as commit messages but now that they can submit through greenhouse I'm removing the submit with a git repo.

### CODE REVIEW

**Comment by tabuchid** [comment]
@brentwatson Good with this?

**Comment by brentwatson** [comment]
How do we expect them to submit through Greenhouse?  Are they still providing a URL to a repo?

**Comment by tabuchid** [comment]
Greenhouse gives them a submission link which gives them a upload form. So they'd just upload a zip.

**Comment by tabuchid** [comment]
They could still give a URL to a repo if they want but I don't think it should be a requirement anymore.

**Comment by brentwatson** [comment]
I think we should be clear about how we want the submission.  Example "Please provide a link to a git/mecural repo in your Greenhouse submission."

**Comment by lra** [comment]
sup?

**Comment by tabuchid** [comment]
Woops. Merging this. Greenhouse sends a link to a upload form with the email telling them about the test.

**Pull request merged**
